In [17]:
import pandas as pd
pd.set_option('display.max_columns', 5)
print('Setup complete.')

Setup complete.

## 1.

In the cell below, create a DataFrame `fruits` that looks like this:

![](https://storage.googleapis.com/kaggle-media/learn/images/Ax3pp2A.png)

In [18]:
fruits = pd.DataFrame({'Apples': [30], 'Bananas': [21]})
fruits

   Apples  Bananas
0      30       21

## 2.

Create a dataframe `fruit_sales` that matches the diagram below:

![](https://storage.googleapis.com/kaggle-media/learn/images/CHPn7ZF.png)

In [19]:
fruit_sales = pd.DataFrame({'Apples': [35, 41], 'Bananas': [21, 34]}, index=['2017 Sales', '2018 Sales'])
fruit_sales

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

## 3.

Create a variable `ingredients` with a Series that looks like:

```
Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object
```

In [20]:
ingredients = pd.Series(['4 cups', '1 cup', '2 large', '1 can'], index=['Flour', 'Milk', 'Eggs', 'Spam'], name='Dinner')
ingredients

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: str

## 4.

Read the following csv dataset of wine reviews into a DataFrame called `reviews`:

![](https://storage.googleapis.com/kaggle-media/learn/images/74RCZtU.png)

The filepath to the csv file is `../input/wine-reviews/winemag-data_first150k.csv`. The first few lines look like:

```
,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,"This tremendous 100% varietal wine[...]",Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and[...]",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,,Tinta de Toro,Bodega Carmen Rodríguez
```

In [21]:
reviews = pd.read_csv('winemag-data_first150k.csv', index_col=0)
reviews

,country,description,...,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,...,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",...,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,...,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",...,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",...,Provence red blend,Domaine de la Bégude
...,...,...,...,...,...
150925,Italy,Many people feel Fiano represents southern Ita...,...,White Blend,Feudi di San Gregorio
150926,France,"Offers an intriguing nose with ginger, lime an...",...,Champagne Blend,H.Germain
150927,Italy,This classic example comes from a cru vineyard...,...,White Blend,Terredora
150928,France,"A perfect salmon shade, with scents of peaches...",...,Champagne Blend,Gosset
150929,Italy,More Pinot Grigios should taste like this. A r...,...,Pinot Grigio,Alois Lageder

## 5.

Run the cell below to create and display a DataFrame called `animals`:

In [23]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

##### In the cell below, write code to save this DataFrame to disk as a csv file with the name `cows_and_goats.csv`.

In [24]:
animals.to_csv('cows_and_goats.csv')