In [12]:
import pandas as pd
pd.set_option('display.max_rows', 500)

In [10]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

   Yes   No
0   50  131
1   21    2

In [16]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.', None],
              'Sue': ['Pretty good.', 'Bland.', 'salam']},
             index=['Product A', 'Product B', 'Hello'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.
Hello                NaN         salam

In [19]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [20]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

In [27]:
wine_reviews = pd.read_csv("../datasets/wine-reviews/winemag-data-130k-v2.csv")

In [28]:
wine_reviews.shape

(129971, 14)

In [29]:
wine_reviews.head()

   Unnamed: 0   country  ...         variety               winery
0           0     Italy  ...     White Blend              Nicosia
1           1  Portugal  ...  Portuguese Red  Quinta dos Avidagos
2           2        US  ...      Pinot Gris            Rainstorm
3           3        US  ...        Riesling           St. Julian
4           4        US  ...      Pinot Noir         Sweet Cheeks

[5 rows x 14 columns]

In [31]:
wine_reviews = pd.read_csv("../datasets/wine-reviews/winemag-data-130k-v2.csv", index_col=0)

In [32]:
wine_reviews.head()

,country,description,...,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",...,White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",...,Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",...,Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",...,Pinot Noir,Sweet Cheeks